name: test

on:
  push:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        number:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
    runs-on: windows-latest
    steps:
      - uses: Raku/setup-raku@v1
      - run: zef install --/test --trace TAP
