name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    name: attempt ${{ matrix.attempt }}
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'
        attempt:
          - 1
          - 2
          - 3
          - 4
          - 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -I. t
