name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
      - name: Run Tests
        run: raku -I. t\01-basic.rakutest
