name: test

on:
  push:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Raku/setup-raku@v1
      - run: zef --version
      - run: zef upgrade --/test --trace zef
