name: test

on:
  push:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        module:
          - TAP:ver<0.3.9>
          - TAP:ver<0.3.10>
          - TAP:ver<0.3.11>
    runs-on: windows-latest
    steps:
      - uses: Raku/setup-raku@v1
      - run: zef upgrade --/test zef
      - run: zef install --/test --trace '"${{ matrix.module }}"'
